### ISSUE TITLE
ImportError: No module named 'reader'

### ISSUE THREAD

**Issue by ballardt** [HamedMP/ImageFlow#8]
I'm currently running Jupyter notebook using [tensorflow-notebook ](https://github.com/jupyter/docker-stacks/tree/master/tensorflow-notebook). When I try `import imageflow`, I get the following:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-f680d40931f4> in <module>()
----> 1 from imageflow import *

/opt/conda/lib/python3.5/site-packages/imageflow/__init__.py in <module>()
     27 
     28 from imageflow import *
---> 29 from reader import read_and_decode
     30 
     31 __author__ = 'HANEL'

ImportError: No module named 'reader'
```

Might-be-relevant-software versions:
Python - 3.5.2
Jupyter - 4.1.1
numpy - 1.10.4
Pillow - 3.2.0
tensorflow - 0.9.0
imageflow - 0.0.2

EDIT: Looks like it's a problem with Jupyter notebook, as everything works fine from the command line, so I'll close this.

**Comment by HamedMP** [comment]
Dear @ballardt 
I just see this, did your problem solved? and if yes, how?

Thanks.

**Comment by ballardt** [comment]
I was getting this error when I tried to import ImageFlow from within Jupyter Notebook. It doesn't occur when I do so in a `.py` file and run the file from the command line with `python example.py`. I would guess that it's a problem with Jupyter Notebook.

**Comment by nguyen14ck** [comment]
I got the same error on both Windows 10 and CentOS 7 (console, Jupyter and Visual Studio Code). My software versions are:
Python 3.5.2 (Anaconda 4.2 64bit)
Jupyter 5.1 (Anaconda 4.2)
Visual Studio Code 1.8 + Python extension 0.56
Tensorflow 0.12.1
ImageFlow 0.2
Could you help? Thanks.

**Comment by HamedMP** [comment]
Hi @nguyen14ck, thanks for reaching out.
As @ballardt stated, this has to be because of Jupyter, more exactly because in the code I use normal Session rather than InteractiveSession. 
I will add support for Jupyter by adding InteractiveSession. Also, contributions are welcomed.
